name: Docker Image CI

on:
  push:
    branches: [ "master", "products", "2-hours-orders" ]
  pull_request:
    branches: [ "master", "products", "2-hours-orders" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eisajanyan/nopcommerce:${{ github.run_number }}-${{ github.sha }}
          file: Dockerfile
          context: .
    
